name: Auto-close issues with specific labels

on:
  issues:
    types: [labeled]

jobs:
  close-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: github.event.label.name == 'completed' || github.event.label.name == 'wontfix'
    steps:
      - name: Close Issue
        run: |
          gh issue close ${{ github.event.issue.number }} --repo ${{ github.repository }} --comment "This issue has been automatically closed because it was labeled as '${{ github.event.label.name }}'."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}